version: '3'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DB_USER: 'webuser'
      DB_PASSWORD: 'webpass'
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_DATABASE_NAME: 'go_mysql8_development'
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
  db:
    platform: linux/x86_64
    image: mysql:8.0.21
    ports:
      - '3306:3306'
    volumes:
      - go_mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'webuser'
      MYSQL_PASSWORD: 'webpass'
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'go_mysql8_development'
volumes:
  go_mysql_data:
